module.exports = { 
    ALREADY_EXIST: 'ALREADY_EXIST',
    INVALID_DATA: 'INVALID_DATA',
    SOMETHING_WRONG: 'SOMETHING_WRONG',
    CREATED: 'CREATED',
    INPUT_CORRECT_EMAIL: 'INPUT_CORRECT_EMAIL',
    INPUT_PASSWORD: 'INPUT_PASSWORD',
    UNCORRECT_DATA: 'UNCORRECT_DATA',
    UNCORRECT_PASSWORD: 'UNCORRECT_PASSWORD',
    NOT_FOUND: 'NOT_FOUND',
    NO_AUTHORIZATION: 'NO AUTHORIZATION'
}