export const LOG_IN = 'AUTH/LOG_IN',
             LOG_OUT = 'LOG_OUT',
             SET_AVATAR = 'SET_AVATAR',
             OPEN_CHANGE_AVATAR_WINDOW = 'OPEN_CHANGE_AVATAR_WINDOW',
             CLOSE_CHANGE_AVATAR_WINDOW = 'CLOSE_CHANGE_AVATAR_WINDOW',
             ADD_USERS_IN_SEARCH = 'ADD_USERS_IN_SEARCH',
             CLEAR_USERS_IN_SEARCH = 'CLEAR_USERS_IN_SEARCH'